const sources=[
{id:'amazon',company:'Amazon',type:'算法 / OA / 系统设计',title:'SDE II Online Assessment + interview loop',claim:'官方明确说明：90 分钟两道 coding、约 15 分钟 system design、work style；技术面试还会考 coding 和 system design。',url:'https://www.amazon.jobs/content/en/how-we-hire/sde-ii-interview-prep',source:'Amazon Jobs · SDE II Interview Prep',skills:['coding','system','behavior']},
{id:'microsoft',company:'Microsoft',type:'真实 IDE / coding / testing',title:'Technical interviewing',claim:'官方指南要求在第三方编码工具中运行和编译代码，解释设计选择，并在完成后测试边界、错误条件和安全影响。',url:'https://careers.microsoft.com/v2/global/en/hiring-tips/technical-interviewing.html',source:'Microsoft Careers · Technical interviewing',skills:['coding','debug']},
{id:'wise',company:'Wise',type:'结对编程 / 系统设计',title:'Backend Pair Programming Interviews',claim:'官方流程为约 60 分钟协作编码，评估技术能力、问题拆解、可维护性、沟通与对反馈的响应；另设 system design。',url:'https://wise.jobs/backend-pair-programming-interviews',source:'Wise Jobs · Backend Pair Programming Interviews',skills:['pair','coding']},
{id:'opslevel',company:'OpsLevel',type:'工作模拟 / 结对 / 深挖',title:'Senior Software Developer Interview Process',claim:'官方流程模拟日常工作：最多 90 分钟 pair programming、需求与数据建模、system design、技术深挖。',url:'https://www.opslevel.com/interview-processes/software-developer',source:'OpsLevel · Senior Software Developer Interview Process',skills:['pair','system','behavior']},
{id:'runna',company:'Runna',type:'take-home / 答辩',title:'Take-home technical task',claim:'公开职位流程说明 take-home 约 3–4 小时，之后用技术面试讨论作业与通用技术问题；具体岗位会变化。',url:'https://public.runna.com/People-Talent-Coordinator-1a1bbd1a4485800e8172fcf4ba3299d9',source:'Runna · Public role process',skills:['takehome','behavior']},
{id:'google',company:'Google',type:'代码理解 / AI 辅助（试点）',title:'Code comprehension as an AI-assisted interview pattern',claim:'这是部分团队/岗位的试点或报道，不应写成 Google 全公司统一流程；训练重点是读代码、调试、验证 AI 输出。',url:'https://careers.google.com/',source:'Google Careers · 具体岗位需核实',skills:['debug','ai']},
{id:'trail',company:'Trail of Bits',type:'安全审查 / take-home',title:'Security-focused technical exercise',claim:'工程岗位公开流程长期强调安全漏洞分析与技术讨论；适合训练代码审查、威胁建模与证据表达。',url:'https://www.trailofbits.com/careers/',source:'Trail of Bits · Careers',skills:['review','takehome']},
{id:'meta',company:'Meta',type:'AI-native coding（政策/岗位相关）',title:'AI-native coding interview',claim:'AI-native 说法必须按具体岗位页面和面试邀请核实；政策可能随团队、语言和地区变化，训练以人主导、验证输出为准。',url:'https://www.metacareers.com/careers',source:'Meta Careers · Careers portal',skills:['ai','coding']}
];
const methods=[{id:'coding',name:'算法与数据结构',desc:'识别问题模型，写出可运行、可解释、可测试的代码。',metric:'02 / 08'},{id:'system',name:'系统设计',desc:'从需求、规模、边界到可靠性和演进做技术权衡。',metric:'03 / 08'},{id:'behavior',name:'项目与行为',desc:'用真实经历证明影响力、责任感、取舍与反思。',metric:'02 / 08'},{id:'debug',name:'调试与代码理解',desc:'基于证据复现、定位、修复，并验证没有回归。',metric:'02 / 08'},{id:'review',name:'代码审查',desc:'优先发现正确性、安全、并发、兼容性和测试风险。',metric:'01 / 08'},{id:'pair',name:'结对编程',desc:'共享思路、拆任务、接纳反馈，在协作中交付。',metric:'02 / 08'},{id:'takehome',name:'Take-home 工作样本',desc:'在有限时间内完成清晰、可测试、能答辩的交付物。',metric:'02 / 08'},{id:'ai',name:'AI 辅助工程',desc:'理解问题、拆分任务、审查 diff、运行验证，保持人类判断权。',metric:'02 / 08'}];
const caseExercises={
amazon:{title:'模拟 Amazon SDE II OA',kind:'限时结构化回答',prompt:'你有 90 分钟完成两道 coding 题，之后还有 system design 与 work style。请写出时间分配、提交前验证清单、卡住时的切换策略。',checks:['先澄清约束并写出暴力解','代码可运行且覆盖边界','说明复杂度并保留时间复核']},
microsoft:{title:'模拟 Microsoft coding + testing',kind:'代码与测试',prompt:'实现分页函数后，面试官要求你在第三方工具中运行、编译并测试。请列出至少 4 个边界测试，并说明一个安全风险。',checks:['空结果与 page 越界','total 为 0 或负数','整数溢出或非法输入','测试失败时能定位根因']},
wise:{title:'模拟 Wise 结对编程',kind:'协作脚本',prompt:'你和面试官共同实现一个小功能。请把开场 5 分钟的沟通写成三句话：确认需求、比较方案、邀请反馈。',checks:['先复述需求和验收标准','说出取舍而不是默默编码','持续运行小测试并回应反馈']},
opslevel:{title:'模拟 OpsLevel 工作场景',kind:'需求到设计',prompt:'请为在线文件转换服务列出 5 个澄清问题，并写出上传、任务、队列、转换、结果通知的最小组件链路。',checks:['用户和核心流程明确','异步任务有状态和重试','讨论失败、幂等与可观测性']},
runna:{title:'模拟 Runna take-home',kind:'限时交付计划',prompt:'你只有 3–4 小时完成一个小型数据任务。请写出交付范围、时间分配、README 必须包含的内容，以及后续答辩准备。',checks:['先锁定核心路径和范围','包含测试、运行说明和已知限制','能解释技术选择并接受现场改需求']},
google:{title:'模拟代码理解与 AI 验证',kind:'调试证据链',prompt:'AI 给出一份看似合理的修复。请写出接受 diff 前的 5 个验证动作，并说明如何证明没有引入回归。',checks:['先阅读调用链和需求','用最小复现或测试验证','人工审查每个 diff，不盲信模型']},
trail:{title:'模拟 Trail of Bits 安全审查',kind:'代码审查',prompt:'审查一个处理用户上传文件的 API。请按优先级列出 3 个安全风险，并为最高风险提出可复现测试。',checks:['输入校验与路径穿越','权限与敏感信息泄露','给出攻击场景和修复验证']},
meta:{title:'模拟 AI-native coding',kind:'AI 协作协议',prompt:'把一个模糊需求拆成 3 个适合交给 AI 的小任务，并为每个任务写验收标准、上下文边界和人工验证方式。',checks:['人先定义问题和边界','每个输出都有可执行验收标准','能解释何时停止调用 AI 并自己判断']}
};
const quiz=[{q:'Microsoft 官方技术面试指南明确要求什么？',a:['只写伪代码，不必运行','在第三方工具运行/编译并测试边界','只考算法，不考测试','必须使用指定语言'],correct:1,why:'Microsoft Careers 明确提到运行、编译、测试和安全/边界条件。',source:'microsoft'},{q:'Wise 后端结对编程主要评估哪组能力？',a:['背诵冷门算法','只看最终代码行数','技术能力、拆解、可维护性、沟通与反馈','只看系统设计'],correct:2,why:'Wise 将技术能力、问题解决、代码结构、沟通协作列为核心。',source:'wise'},{q:'Amazon SDE II OA 的 coding 部分官方描述是？',a:['90 分钟 2 道题','15 分钟 1 道题','无时间限制的 take-home','只做行为题'],correct:0,why:'Amazon 官方页面写明 90 minutes for 2 questions。',source:'amazon'},{q:'AI 辅助编程训练最重要的闭环是什么？',a:['让 AI 一次性写完全部代码','只比较提示词长短','人先理解，AI 执行，逐 diff 验证并测试','避免所有工具'],correct:2,why:'这是跨公司政策变化下最稳妥的通用能力表述。',source:'meta'}];
const plans=[['W1','算法模式与口述','coding','两道同一模式题 + 一次 45 分钟模拟'],['W2','测试、边界与复杂度','coding','编译器实验：实现并验证一个函数'],['W3','系统设计基本框架','system','需求澄清、估算、API、数据模型'],['W4','项目档案与行为故事','behavior','三份项目档案 + 五轮追问'],['W5','调试与代码理解','debug','陌生仓库入场 + 最小复现'],['W6','审查与协作','review','审查真实 PR + 结对任务'],['W7','限时工作样本','takehome','3 小时微型项目 + 30 分钟答辩'],['W8','AI 协作综合模拟','ai','理解 → 实现 → 测试 → 审查 → 解释']];
const state={completed:JSON.parse(localStorage.getItem('signal-completed')||'[]'),method:'coding',sourceId:'amazon',quizIndex:0};
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const codeStarter='function isValidPage(page, total) {\n  // write your solution\n}';
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}function save(){localStorage.setItem('signal-completed',JSON.stringify(state.completed));updateProgress()}function updateProgress(){const p=Math.round(state.completed.length/20*100);$('#progressLabel').textContent=`${Math.min(100,p)}% complete`}
function renderOverview(){const cards=sources.map(s=>`<article class="card case-card"><span class="tag">${s.company} · ${s.type}</span><h3>${s.title}</h3><p>${s.claim}</p><div class="card-foot"><a href="${s.url}" target="_blank" rel="noreferrer">阅读原始来源 ↗</a><button class="link-btn" data-source-practice="${s.id}">${state.completed.includes('case:'+s.id)?'已完成 ✓':'对应练习 →'}</button></div></article>`).join('');$('#view-overview').innerHTML=`<div class="hero"><div><div class="eyebrow">Evidence / Practice / Transfer</div><h1>别只会刷题。<br/><em>训练成为能交付的人。</em></h1><p>一个把现代软件工程招聘方式拆成“证据—知识—练习—反馈”的阅读器与训练场。</p></div><div class="hero-note"><strong>Today’s signal</strong><p>现代面试越来越接近真实工作：读代码、协作、验证、解释取舍。</p></div></div><div class="metrics"><div class="metric"><b>${sources.length}</b><span>已核查案例节点</span></div><div class="metric"><b>08</b><span>能力模块</span></div><div class="metric"><b>08</b><span>周训练路径</span></div><div class="metric"><b>${state.completed.length}</b><span>已完成练习</span></div></div><div class="section-head"><div><h2>能力地图</h2><p>从招聘信号出发，进入对应练习。</p></div><button class="link-btn" data-go="practice">打开练习实验室 →</button></div><div class="grid">${methods.map(m=>`<article class="card method-card"><span class="tag">${m.metric}</span><h3>${m.name}</h3><p>${m.desc}</p><div class="card-foot"><span>${sources.filter(s=>s.skills.includes(m.id)).length} 个来源案例</span><button class="link-btn" data-method="${m.id}">练习 →</button></div></article>`).join('')}</div><div class="section-head"><div><h2>来源案例 → 对应练习</h2><p>每个来源都有一个可进入、可提交、可记录的具体任务。</p></div><button class="link-btn" data-go="evidence">进入证据库 →</button></div><div class="grid">${cards}</div>`}
function renderEvidence(){const s=sources.find(x=>x.id===state.sourceId)||sources[0],ex=caseExercises[s.id];$('#view-evidence').innerHTML=`<div class="eyebrow">Source reader / ${sources.length} verified nodes</div><div class="section-head"><div><h1 style="font:600 48px 'Space Grotesk';letter-spacing:-.06em;margin:12px 0 0">证据库</h1><p>每个来源案例都有对应练习；范围有限的试点会明确标注。</p></div></div><div class="evidence-layout"><div class="side-list">${sources.map(x=>`<button class="${x.id===s.id?'active':''}" data-source="${x.id}">${x.company}<br><small>${x.type}</small></button>`).join('')}</div><article class="card detail"><span class="tag">${s.company} · ${s.type}</span><h2>${s.title}</h2><p class="claim">${s.claim}</p><div class="source-row"><a class="source-link" href="${s.url}" target="_blank" rel="noreferrer">${s.source} ↗</a><span class="tag">训练节点：${s.skills.join(' / ')}</span></div><div class="section-head"><div><h2>对应练习：${ex.title}</h2><p>${ex.kind} · ${state.completed.includes('case:'+s.id)?'已完成':'尚未完成'}</p></div><button class="primary" data-source-practice="${s.id}">进入此案例练习 →</button></div><p class="explain">“公司明确写出的流程”和“我们据此设计的练习”分开呈现。对于 Google、Meta 等快速变化的 AI 政策，以具体岗位邀请和招聘方说明为准。</p></article></div>`}
function renderPractice(){const q=quiz[state.quizIndex%quiz.length],m=methods.find(x=>x.id===state.method),s=sources.find(x=>x.id===state.sourceId),ex=caseExercises[s.id],done=state.completed.includes('case:'+s.id);$('#view-practice').innerHTML=`<div class="eyebrow">Practice lab / ${m.name}</div><div class="section-head"><div><h1 style="font:600 48px 'Space Grotesk';letter-spacing:-.06em;margin:12px 0 0">练习实验室</h1><p>能力练习与来源案例练习都在这里完成。</p></div><div class="filters">${methods.map(x=>`<button class="filter ${x.id===state.method?'active':''}" data-method="${x.id}">${x.name}</button>`).join('')}</div></div><div class="grid" style="grid-template-columns:1fr 1fr"><article class="card exercise"><span class="tag">基础知识 · 随机问答 · 来源：${sources.find(x=>x.id===q.source).company}</span><h2>${q.q}</h2><div class="choice-list">${q.a.map((a,i)=>`<button class="choice" data-answer="${i}">${a}</button>`).join('')}</div><p id="quizExplain" class="explain">选择一个答案，系统会告诉你为什么。</p><button class="secondary" id="nextQuiz">下一题 →</button></article><article class="card exercise"><span class="tag">代码验证 · JavaScript</span><h2>实现一个安全的边界检查</h2><p>实现 <code>isValidPage(page, total)</code>，并运行 4 个边界测试。</p><div class="code-grid"><div><textarea id="codeEditor" class="code-editor">${codeStarter}</textarea><button class="run-btn" id="runCode">运行验证</button></div><pre id="codeOutput" class="output">等待运行…</pre></div><button class="secondary" id="completeCode" style="margin-top:12px">标记已掌握</button></article></div><div class="card exercise" style="margin-top:14px"><span class="tag">来源案例练习 · ${s.company} · ${ex.kind}</span><div class="section-head"><div><h2>${ex.title}</h2><p>${ex.prompt}</p></div><span class="tag">${done?'已完成 ✓':'1 对 1 映射'}</span></div><div class="choice-list">${ex.checks.map((c,i)=>`<label class="choice"><input type="checkbox" data-case-check="${i}" style="margin-right:10px">${c}</label>`).join('')}</div><textarea id="caseAnswer" class="key-input" style="min-height:120px;resize:vertical" placeholder="写下你的回答、设计或排查路径……"></textarea><button class="primary" id="completeCase">${done?'再次完成':'提交并标记掌握'}</button></div><div class="card exercise" style="margin-top:14px"><span class="tag">AI 协作实验 · DeepSeek</span><h2>人主导、AI 执行、逐 diff 验证</h2><textarea id="aiPrompt" class="key-input" style="min-height:110px;resize:vertical" placeholder="写清上下文、任务和验收标准……"></textarea><div><button class="primary" id="runAi">发送给 DeepSeek</button><button class="secondary" data-go="settings" style="margin-left:8px">配置 Key</button></div><pre id="aiOutput" class="output" style="margin-top:14px;min-height:120px">等待你的任务…</pre></div>`}
function renderPlan(){const rows=plans.map((p,i)=>`<div class="plan-row"><div class="week">${p[0]}</div><div><h3>${p[1]}</h3><p>${p[3]} · 对应：${methods.find(m=>m.id===p[2]).name}</p></div><div class="progress"><i style="width:${state.completed.includes('w'+i)?100:0}%"></i></div></div>`).join('');$('#view-plan').innerHTML=`<div class="eyebrow">Curriculum / 8 weeks</div><h1 style="font:600 58px 'Space Grotesk';letter-spacing:-.07em;margin:12px 0">训练路径</h1><p style="color:var(--muted);max-width:650px;line-height:1.6">每周目标对应能力地图中的节点；每个来源案例另有一项具体练习。</p><div class="card" style="padding:10px 25px;margin-top:30px">${rows}</div><button class="primary" id="markWeek" style="margin-top:20px">完成下一周 →</button>`}
function renderSettings(){const key=localStorage.getItem('deepseek-key')||'';$('#view-settings').innerHTML=`<div class="eyebrow">Local only / privacy</div><h1 style="font:600 58px 'Space Grotesk';letter-spacing:-.07em;margin:12px 0">本机设置</h1><div class="card setting-card"><h3>DeepSeek API</h3><p>Key 只保存在浏览器本机 localStorage，不会进入 Git 或页面源码。</p><input class="key-input" id="keyInput" type="password" value="${esc(key)}" placeholder="sk-…"/><button class="primary" id="saveKey">保存到本机</button><span id="keyStatus" style="margin-left:10px;color:var(--muted);font-size:12px">${key?'已配置':'未配置'}</span></div><div class="card setting-card" style="margin-top:14px"><h3>数据与隐私</h3><p>练习进度和 API Key 均为设备本地数据。清空后不能恢复。</p><button class="secondary" id="clearData">清空本机进度</button></div>`}
function render(){renderOverview();renderEvidence();renderPractice();renderPlan();renderSettings();updateProgress()}function show(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));$('#view-'+v).classList.add('active-view');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));render()}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){show(nav.dataset.view);return}const go=e.target.closest('[data-go]');if(go){show(go.dataset.go);return}const mp=e.target.closest('[data-method]');if(mp){state.method=mp.dataset.method;show('practice');return}const sp=e.target.closest('[data-source-practice]');if(sp){state.sourceId=sp.dataset.sourcePractice;show('practice');return}const src=e.target.closest('[data-source]');if(src){state.sourceId=src.dataset.source;renderEvidence();return}if(e.target.id==='nextQuiz'){state.quizIndex++;renderPractice();return}const ans=e.target.closest('[data-answer]');if(ans){const q=quiz[state.quizIndex%quiz.length];document.querySelectorAll('.choice').forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add('correct')});if(+ans.dataset.answer!==q.correct)ans.classList.add('wrong');$('#quizExplain').textContent=q.why;state.completed=[...new Set([...state.completed,'q'+state.quizIndex])];save();return}if(e.target.id==='runCode'){const out=$('#codeOutput');try{const fn=new Function($('#codeEditor').value+'; return typeof isValidPage === "function" ? isValidPage : null;')();if(!fn)throw Error('请定义 isValidPage');const tests=[[1,3,true],[0,3,false],[4,3,false],[2,2,true]];out.textContent=tests.map(([a,b,x])=>`${fn(a,b)===x?'✓':'✗'} isValidPage(${a}, ${b}) → ${fn(a,b)}（期望 ${x}）`).join('\n');if(tests.every(([a,b,x])=>fn(a,b)===x)){out.textContent+='\n\n全部测试通过。';state.completed=[...new Set([...state.completed,'code'])];save()}}catch(err){out.textContent='运行失败：'+err.message}return}if(e.target.id==='completeCode'){state.completed=[...new Set([...state.completed,'code'])];save();toast('已记录：代码验证');return}if(e.target.id==='completeCase'){const checks=[...document.querySelectorAll('[data-case-check]')];if(checks.some(x=>!x.checked)||!$('#caseAnswer').value.trim()){toast('请完成全部检查点并写下回答');return}state.completed=[...new Set([...state.completed,'case:'+state.sourceId])];save();renderPractice();toast('来源案例练习已完成');return}if(e.target.id==='saveKey'){localStorage.setItem('deepseek-key',$('#keyInput').value.trim());$('#keyStatus').textContent=$('#keyInput').value.trim()?'已配置':'未配置';toast('已保存到本机');return}if(e.target.id==='clearData'){localStorage.removeItem('signal-completed');localStorage.removeItem('deepseek-key');state.completed=[];render();toast('本机数据已清空');return}if(e.target.id==='markWeek'){const n=plans.findIndex((_,i)=>!state.completed.includes('w'+i));if(n>=0){state.completed.push('w'+n);save();renderPlan();toast(`已完成 ${plans[n][0]}：${plans[n][1]}`)}return}if(e.target.id==='randomBtn'){state.method=methods[Math.floor(Math.random()*methods.length)].id;show('practice')}});
document.addEventListener('click',async e=>{if(e.target.id!=='runAi')return;const key=localStorage.getItem('deepseek-key'),prompt=$('#aiPrompt').value.trim(),out=$('#aiOutput');if(!key){out.textContent='请先在“本机设置”保存 DeepSeek Key。';return}if(!prompt){out.textContent='请先写出任务、上下文和验收标准。';return}e.target.disabled=true;e.target.textContent='请求中…';try{const r=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify({model:'deepseek-chat',temperature:.2,messages:[{role:'system',content:'你是软件工程面试训练教练。先指出假设，再给出可验证建议，不要替用户直接完成全部工作。'},{role:'user',content:prompt}]})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||'请求失败');out.textContent=d.choices?.[0]?.message?.content||'模型没有返回文本。';state.completed=[...new Set([...state.completed,'ai'])];save()}catch(err){out.textContent='AI 请求失败：'+err.message+'\n\n请检查 Key、网络和浏览器跨域策略。'}finally{e.target.disabled=false;e.target.textContent='发送给 DeepSeek'}});render();
