const sources=[
 {id:'amazon',company:'Amazon',type:'算法 / OA / 系统设计',title:'SDE II Online Assessment + interview loop',claim:'官方明确说明：90 分钟两道 coding、约 15 分钟 system design、work style；技术面试还会考 coding 和 system design。',url:'https://www.amazon.jobs/content/en/how-we-hire/sde-ii-interview-prep',source:'Amazon Jobs · SDE II Interview Prep',skills:['coding','system','behavior']},
 {id:'microsoft',company:'Microsoft',type:'真实 IDE / coding / testing',title:'Technical interviewing',claim:'官方指南要求在第三方编码工具中运行和编译代码，解释设计选择，并在完成后测试边界、错误条件和安全影响。',url:'https://careers.microsoft.com/v2/global/en/hiring-tips/technical-interviewing.html',source:'Microsoft Careers · Technical interviewing',skills:['coding','debug']},
 {id:'wise',company:'Wise',type:'结对编程 / 系统设计',title:'Backend Pair Programming Interviews',claim:'官方流程为约 60 分钟协作编码，评估技术能力、问题拆解、可维护性、沟通与对反馈的响应；另设 system design。',url:'https://wise.jobs/backend-pair-programming-interviews',source:'Wise Jobs · Backend Pair Programming Interviews',skills:['pair','coding']},
 {id:'opslevel',company:'OpsLevel',type:'工作模拟 / 结对 / 深挖',title:'Senior Software Developer Interview Process',claim:'官方流程模拟日常工作：最多 90 分钟 pair programming、需求与数据建模、system design、技术深挖。',url:'https://www.opslevel.com/interview-processes/software-developer',source:'OpsLevel · Senior Software Developer Interview Process',skills:['pair','system','behavior']},
 {id:'runna',company:'Runna',type:'take-home / 答辩',title:'Take-home technical task',claim:'公开职位流程说明 take-home 约 3–4 小时，之后用技术面试讨论作业与通用技术问题；具体岗位会变化。',url:'https://public.runna.com/People-Talent-Coordinator-1a1bbd1a4485800e8172fcf4ba3299d9',source:'Runna · Public role process',skills:['takehome','behavior']},
 {id:'google',company:'Google',type:'代码理解 / AI 辅助（试点）',title:'Code comprehension as an AI-assisted interview pattern',claim:'前文案例应谨慎表述：这是部分团队/岗位的试点或报道，不应当写成 Google 全公司统一流程；训练重点是读代码、调试、验证 AI 输出。',url:'https://blog.google/technology/research/google-ai-interviewing/',source:'Google · AI and interviewing context（需按岗位核实）',skills:['debug','ai']},
 {id:'trail',company:'Trail of Bits',type:'安全审查 / take-home',title:'Security-focused technical exercise',claim:'工程岗位公开流程长期强调安全漏洞分析与技术讨论；适合训练代码审查、威胁建模与证据表达。',url:'https://www.trailofbits.com/careers/',source:'Trail of Bits · Careers',skills:['review','takehome']},
 {id:'meta',company:'Meta',type:'AI-native coding（政策/岗位相关）',title:'AI-native coding interview',claim:'前文引用的 AI-native 说法必须按具体岗位页面和面试邀请核实；平台政策可能随团队、语言和地区变化，训练时以“人主导、验证输出”为准。',url:'https://www.metacareers.com/careers',source:'Meta Careers · Careers portal',skills:['ai','coding']}
];
const methods=[
 {id:'coding',name:'算法与数据结构',desc:'识别问题模型，写出可运行、可解释、可测试的代码。',color:'lime',metric:'02 / 08'},
 {id:'system',name:'系统设计',desc:'从需求、规模、边界到可靠性和演进做技术权衡。',metric:'03 / 08'},
 {id:'behavior',name:'项目与行为',desc:'用真实经历证明影响力、责任感、取舍与反思。',metric:'02 / 08'},
 {id:'debug',name:'调试与代码理解',desc:'基于证据复现、定位、修复，并验证没有回归。',metric:'02 / 08'},
 {id:'review',name:'代码审查',desc:'优先发现正确性、安全、并发、兼容性和测试风险。',metric:'01 / 08'},
 {id:'pair',name:'结对编程',desc:'共享思路、拆任务、接纳反馈，在协作中交付。',metric:'02 / 08'},
 {id:'takehome',name:'Take-home 工作样本',desc:'在有限时间内完成清晰、可测试、能答辩的交付物。',metric:'02 / 08'},
 {id:'ai',name:'AI 辅助工程',desc:'理解问题、拆分任务、审查 diff、运行验证，保持人类判断权。',metric:'02 / 08'}
];
const plans=[['W1','算法模式与口述','coding','两道同一模式题 + 一次 45 分钟模拟'],['W2','测试、边界与复杂度','coding','编译器实验：实现并验证一个函数'],['W3','系统设计基本框架','system','需求澄清、估算、API、数据模型'],['W4','项目档案与行为故事','behavior','三份项目档案 + 五轮追问'],['W5','调试与代码理解','debug','陌生仓库入场 + 最小复现'],['W6','审查与协作','review','审查真实 PR + 结对任务'],['W7','限时工作样本','takehome','3 小时微型项目 + 30 分钟答辩'],['W8','AI 协作综合模拟','ai','理解 → 实现 → 测试 → 审查 → 解释']];
const quiz=[{q:'Microsoft 官方技术面试指南明确要求什么？',a:['只写伪代码，不必运行','在第三方工具运行/编译并测试边界','只考算法，不考测试','必须使用指定语言'],correct:1,why:'Microsoft Careers 明确提到运行、编译、测试和安全/边界条件。',source:'microsoft'}, {q:'Wise 后端结对编程主要评估哪组能力？',a:['背诵冷门算法','只看最终代码行数','技术能力、拆解、可维护性、沟通与反馈','只看系统设计'],correct:2,why:'Wise 将技术能力、问题解决、代码结构、沟通协作列为核心。',source:'wise'}, {q:'Amazon SDE II OA 的 coding 部分官方描述是？',a:['90 分钟 2 道题','15 分钟 1 道题','无时间限制的 take-home','只做行为题'],correct:0,why:'Amazon 官方页面写明 90 minutes for 2 questions。',source:'amazon'}, {q:'AI 辅助编程训练最重要的闭环是什么？',a:['让 AI 一次性写完全部代码','只比较提示词长短','人先理解，AI 执行，逐 diff 验证并测试','避免所有工具'],correct:2,why:'这是跨公司政策变化下最稳妥的通用能力表述。',source:'meta'}];
const state={view:'overview',completed:JSON.parse(localStorage.getItem('signal-completed')||'[]'),method:'coding',quizIndex:0};
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function save(){localStorage.setItem('signal-completed',JSON.stringify(state.completed));updateProgress()}
function updateProgress(){const p=Math.round(state.completed.length/12*100);$('#progressLabel').textContent=`${Math.min(100,p)}% complete`}
function renderOverview(){const cases=sources.slice(0,6).map(s=>`<article class="card case-card"><span class="tag">${s.company} · ${s.type}</span><h3>${s.title}</h3><p>${s.claim}</p><a href="${s.url}" target="_blank" rel="noreferrer">阅读原始来源 ↗</a></article>`).join('');$('#view-overview').innerHTML=`<div class="hero"><div><div class="eyebrow">Evidence / Practice / Transfer</div><h1>别只会刷题。<br/><em>训练成为能交付的人。</em></h1><p>一个把现代软件工程招聘方式拆成“证据—知识—练习—反馈”的阅读器与训练场。每条结论都能回到公开来源，每次练习都产生可见的能力信号。</p></div><div class="hero-note"><strong>Today’s signal</strong><p>现代面试越来越接近真实工作：读代码、协作、验证、解释取舍。算法仍重要，但不再单独代表工程能力。</p></div></div><div class="metrics"><div class="metric"><b>${sources.length}</b><span>已核查案例节点</span></div><div class="metric"><b>08</b><span>能力模块</span></div><div class="metric"><b>08</b><span>周训练路径</span></div><div class="metric"><b id="doneMetric">${state.completed.length}</b><span>已完成练习</span></div></div><div class="section-head"><div><h2>能力地图</h2><p>从招聘信号出发，进入对应练习。</p></div><button class="link-btn" data-go="practice">打开练习实验室 →</button></div><div class="grid">${methods.map(m=>`<article class="card method-card"><span class="tag">${m.metric}</span><h3>${m.name}</h3><p>${m.desc}</p><div class="card-foot"><span>${sources.filter(s=>s.skills.includes(m.id)).length} 个来源案例</span><button class="link-btn" data-method="${m.id}">练习 →</button></div></article>`).join('')}</div><div class="section-head"><div><h2>证据快照</h2><p>只展示已能落到公开原始页面的案例。</p></div><button class="link-btn" data-go="evidence">进入证据库 →</button></div><div class="grid">${cases}</div>`}
function renderEvidence(){const selected=sources.find(s=>s.id===state.method)||sources[0];$('#view-evidence').innerHTML=`<div class="eyebrow">Source reader / ${sources.length} verified nodes</div><div class="section-head"><div><h1 style="font:600 48px 'Space Grotesk';letter-spacing:-.06em;margin:12px 0 0">证据库</h1><p>来源优先级：公司官方招聘页面 ＞ 官方岗位流程 ＞ 高可信报道；范围有限的试点会明确标注。</p></div></div><div class="evidence-layout"><div class="side-list">${sources.map(s=>`<button class="${s.id===selected.id?'active':''}" data-source="${s.id}">${s.company}<br><small>${s.type}</small></button>`).join('')}</div><article class="card detail"><span class="tag">${selected.company} · ${selected.type}</span><h2>${selected.title}</h2><p class="claim">${selected.claim}</p><div class="source-row"><a class="source-link" href="${selected.url}" target="_blank" rel="noreferrer">${selected.source} ↗</a><span class="tag">训练节点：${selected.skills.join(' / ')}</span></div><div class="section-head"><div><h2>核查备注</h2><p>这是案例能证明的范围，不自动外推到公司所有团队。</p></div></div><p class="explain">本阅读器将“公司明确写出的流程”和“我们据此设计的练习”分开。你可以用来源链接复核原文，再进入练习实验室完成对应任务。对于 Meta、Google 等快速变化的 AI 面试政策，以当前岗位邀请和招聘方说明为准。</p></article></div>`}
  // write your solution
}</textarea><button class="run-btn" id="runCode">运行验证</button></div><pre id="codeOutput" class="output">等待运行…</pre></div><button class="secondary" id="completeCode" style="margin-top:12px">标记已掌握</button></article></div><div class="card exercise" style="margin-top:14px"><span class="tag">AI 协作实验</span><h2>人主导、AI 执行、逐 diff 验证</h2><p>在“本机设置”保存你的 DeepSeek Key 后，可以向 AI 发送一个边界明确的小任务；系统会把请求、回答和你的验证记录留在本机，不会写入仓库。</p><button class="primary" data-go="settings">配置 DeepSeek →</button></div>`}
function renderPractice(){const q=quiz[state.quizIndex%quiz.length];const m=methods.find(x=>x.id===state.method);$('#view-practice').innerHTML=`<div class="eyebrow">Practice lab / ${m.name}</div><div class="section-head"><div><h1 style="font:600 48px 'Space Grotesk';letter-spacing:-.06em;margin:12px 0 0">练习实验室</h1><p>每次练习都对应知识节点，并链接到具体来源。</p></div><div class="filters">${methods.map(x=>`<button class="filter ${x.id===state.method?'active':''}" data-method="${x.id}">${x.name}</button>`).join('')}</div></div><div class="grid" style="grid-template-columns:1fr 1fr"><article class="card exercise"><span class="tag">基础知识 · 随机问答 · 来源：${sources.find(s=>s.id===q.source).company}</span><h2>${q.q}</h2><div class="choice-list">${q.a.map((a,i)=>`<button class="choice" data-answer="${i}">${a}</button>`).join('')}</div><p id="quizExplain" class="explain">选择一个答案，系统会告诉你为什么。</p><button class="secondary" id="nextQuiz">下一题 →</button></article><article class="card exercise"><span class="tag">代码验证 · JavaScript</span><h2>实现一个安全的边界检查</h2><p>写一个函数 <code>isValidPage(page, total)</code>：page 和 total 为整数，返回 page 是否在 1..total 范围内。先自己写，再运行测试。</p><div class="code-grid"><div><textarea id="codeEditor" class="code-editor">function isValidPage(page, total) {
  // write your solution
}</textarea><button class="run-btn" id="runCode">运行验证</button></div><pre id="codeOutput" class="output">等待运行…</pre></div><button class="secondary" id="completeCode" style="margin-top:12px">标记已掌握</button></article></div><div class="card exercise" style="margin-top:14px"><span class="tag">AI 协作实验 · DeepSeek</span><h2>人主导、AI 执行、逐 diff 验证</h2><p>先写清上下文和验收标准，再让模型给出方案。Key 只从本机读取，浏览器直接请求 DeepSeek，不经过本网站服务器。</p><textarea id="aiPrompt" class="key-input" style="min-height:110px;resize:vertical" placeholder="例如：请审查这段分页函数，列出三个边界测试，并解释每个测试为什么重要。"></textarea><div><button class="primary" id="runAi">发送给 DeepSeek</button><button class="secondary" data-go="settings" style="margin-left:8px">配置 Key</button></div><pre id="aiOutput" class="output" style="margin-top:14px;min-height:120px">等待你的任务…</pre></div>`}
  // write your solution
}</textarea><button class="run-btn" id="runCode">运行验证</button></div><pre id="codeOutput" class="output">等待运行…</pre></div><button class="secondary" id="completeCode" style="margin-top:12px">标记已掌握</button></article></div><div class="card exercise" style="margin-top:14px"><span class="tag">AI 协作实验</span><h2>人主导、AI 执行、逐 diff 验证</h2><p>在“本机设置”保存你的 DeepSeek Key 后，可以向 AI 发送一个边界明确的小任务；系统会把请求、回答和你的验证记录留在本机，不会写入仓库。</p><button class="primary" data-go="settings">配置 DeepSeek →</button></div>`}
function renderPlan(){const rows=plans.map((p,i)=>`<div class="plan-row"><div class="week">${p[0]}</div><div><h3>${p[1]}</h3><p>${p[3]} · 对应：${methods.find(m=>m.id===p[2]).name}</p></div><div class="progress"><i style="width:${state.completed.includes('w'+i)?100:0}%"></i></div></div>`).join('');$('#view-plan').innerHTML=`<div class="eyebrow">Curriculum / 8 weeks</div><h1 style="font:600 58px 'Space Grotesk';letter-spacing:-.07em;margin:12px 0">训练路径</h1><p style="color:var(--muted);max-width:650px;line-height:1.6">不是堆内容，而是让每周目标对应能力地图中的节点；每周完成后留下一个可复盘的工作样本或口头表达。</p><div class="card" style="padding:10px 25px;margin-top:30px">${rows}</div><button class="primary" id="markWeek" style="margin-top:20px">完成下一周 →</button>`}
function renderSettings(){const key=localStorage.getItem('deepseek-key')||'';$('#view-settings').innerHTML=`<div class="eyebrow">Local only / privacy</div><h1 style="font:600 58px 'Space Grotesk';letter-spacing:-.07em;margin:12px 0">本机设置</h1><div class="card setting-card"><h3>DeepSeek API</h3><p>Key 只保存在当前浏览器的 localStorage，不会进入 Git、构建产物或页面源码。请不要在公共电脑保存 Key。若你提到的“恋爱宝典 rag”里有 Key，我无法直接读取另一个应用的秘密，需要你在此处粘贴。</p><input class="key-input" id="keyInput" type="password" value="${esc(key)}" placeholder="sk-…"/><button class="primary" id="saveKey">保存到本机</button><span id="keyStatus" style="margin-left:10px;color:var(--muted);font-size:12px">${key?'已配置':'未配置'}</span></div><div class="card setting-card" style="margin-top:14px"><h3>数据与隐私</h3><p>练习进度和 API Key 均为设备本地数据。清空后不能恢复。</p><button class="secondary" id="clearData">清空本机进度</button></div>`}
function render(){renderOverview();renderEvidence();renderPractice();renderPlan();renderSettings();updateProgress()}
function show(view){state.view=view;document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));$('#view-'+view).classList.add('active-view');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));render()}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){show(nav.dataset.view);return}const go=e.target.closest('[data-go]');if(go){show(go.dataset.go);return}const method=e.target.closest('[data-method]');if(method){state.method=method.dataset.method;show('practice');return}const source=e.target.closest('[data-source]');if(source){state.method=source.dataset.source;renderEvidence();return}const ans=e.target.closest('[data-answer]');if(ans){const q=quiz[state.quizIndex%quiz.length];document.querySelectorAll('.choice').forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add('correct')});if(+ans.dataset.answer!==q.correct)ans.classList.add('wrong');$('#quizExplain').textContent=q.why;state.completed=[...new Set([...state.completed,'q'+state.quizIndex])];save();return}if(e.target.id==='nextQuiz'){state.quizIndex++;renderPractice();return}if(e.target.id==='runCode'){const out=$('#codeOutput');try{const fn=new Function($('#codeEditor').value+'; return typeof isValidPage === "function" ? isValidPage : null;')();if(!fn)throw Error('请定义 isValidPage');const tests=[[1,3,true],[0,3,false],[4,3,false],[2,2,true]];const result=tests.map(([a,b,expected])=>{const actual=fn(a,b);return `${actual===expected?'✓':'✗'} isValidPage(${a}, ${b}) → ${actual}（期望 ${expected}）`}).join('\n');out.textContent=result;if(tests.every(([a,b,x])=>fn(a,b)===x)){out.textContent+='\n\n全部测试通过。';state.completed=[...new Set([...state.completed,'code'])];save()}}catch(err){out.textContent='运行失败：'+err.message}return}if(e.target.id==='completeCode'){state.completed=[...new Set([...state.completed,'code'])];save();toast('已记录：代码验证');return}if(e.target.id==='saveKey'){localStorage.setItem('deepseek-key',$('#keyInput').value.trim());$('#keyStatus').textContent=$('#keyInput').value.trim()?'已配置':'未配置';toast('已保存到本机');return}if(e.target.id==='clearData'){localStorage.removeItem('signal-completed');localStorage.removeItem('deepseek-key');state.completed=[];render();toast('本机数据已清空');return}if(e.target.id==='markWeek'){const next=plans.findIndex((_,i)=>!state.completed.includes('w'+i));if(next>=0){state.completed.push('w'+next);save();renderPlan();toast(`已完成 ${plans[next][0]}：${plans[next][1]}`)}else toast('8 周路径已全部完成');return}if(e.target.id==='randomBtn'){state.method=methods[Math.floor(Math.random()*methods.length)].id;show('practice')}});
document.addEventListener('click',async e=>{if(e.target.id!=='runAi')return;const key=localStorage.getItem('deepseek-key');const prompt=$('#aiPrompt').value.trim();const out=$('#aiOutput');if(!key){out.textContent='请先在“本机设置”保存 DeepSeek Key。';return}if(!prompt){out.textContent='请先写出任务、上下文和验收标准。';return}e.target.disabled=true;e.target.textContent='请求中…';out.textContent='正在等待模型回答…';try{const r=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify({model:'deepseek-chat',temperature:0.2,messages:[{role:'system',content:'你是软件工程面试训练教练。先指出任务中的假设，再给出可验证、简洁的建议；不要替用户直接完成全部工作。'},{role:'user',content:prompt}]})});const data=await r.json();if(!r.ok)throw Error(data.error?.message||'请求失败');out.textContent=data.choices?.[0]?.message?.content||'模型没有返回文本。';state.completed=[...new Set([...state.completed,'ai'])];save()}catch(err){out.textContent='AI 请求失败：'+err.message+'\n\n请检查 Key、网络和浏览器跨域策略。'}finally{e.target.disabled=false;e.target.textContent='发送给 DeepSeek'}});
render();
